services:
  database:
    container_name: PolyglotDB
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3333:3306"
  webservice:
    container_name: Polyglot
    build:
      context: .
      dockerfile: Dockerfile-rest
    ports:
      - "8444:8444"
    depends_on:
      - database
    command: sh -c "/wait && java -jar /usr/app/polyglot.jar"
    environment:
      - WAIT_HOSTS=database:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
version: '3.8'

